### ISSUE TITLE
Slack invite link expired

### ISSUE THREAD

**Issue by shinebayar-g** [kata-containers/community#126]
# Description of problem

Slack invite link expired. https://katacontainers.slack.com/join/shared_invite/enQtMjc5NTIwMTEyMzI0LTBjMDgyMTY2YjU0ZDZiZDgzNDU0ZTI4MWFiNzViY2VmODI3ZTJmZjA2ZGY2M2EyZGVmMzk4MjE5NzNkNzhiY2U

**Comment by grahamwhaley** [comment]
@shinebayar-g - thanks for reporting!
@ttx @ClaireMassey - is this something you can help with?

**Comment by ttx** [comment]
@ClaireMassey said on the channel: "the new Kata slack link is http://bit.ly/katacontainersslack. I had it updated on the website several weeks ago because the old link expired. However, now it appears that the old expired link is again displayed on the website for some reason so will work to get that corrected this week."

**Comment by amshinde** [comment]
This can be closed now as the new Kata slack link has been updated.
