### ISSUE TITLE
Process: backports/stable: should backports contain explicit refs to originals?

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/community#63]
When backport/cherry picking commits or PRs to stable branches, should we require that the commits and/or PR message are updated to include a reference back to the original commits (SHAs), and PR (github #nnn's).

This will:
- make it easier and clearer for reviewers the provenance of the backport
- make the providence trail clearer in the git logs
- but shift the onus onto the submitters to do the work of adding these in (ammending the commit messages for instance)

Yes, you can get the info at present by following the `Fixes: #nnn` link in the PR that is being posted, but it is more work for the reviewers and requires you to hop through github.

Fundamentally this is about providence/crumb-trail and shifting some of the work from the reviewers over to the submitters.

I've added this as an architecture committee topic for 2018-09-17

**Comment by jodh-intel** [comment]
I like the idea of full and easy traceability (without github) but we don't this to be too much of a burden. I'd say that if we vote on doing this, that we whip up something like `kata-backport.sh` that can take some of the pain away. If we require this reference, [`checkcommits`](https://github.com/kata-containers/tests/tree/master/cmd/checkcommits) should be updated to require it for stable branches only.

**Comment by jodh-intel** [comment]
I've just added an explicit ref in https://github.com/kata-containers/runtime/pull/737 as it required a minor rework:

```
Original-master-commit: https://github.com/kata-containers/runtime/commits/23a35c84c92e6ce73366edc575ae875ba4d77473
```

I'm not sure that's the best tag but it's clear I think ;) Also, Since we're cherry-picking anyway, we need to specify the ref to the original commit to do that, hence I think it's not unreasonable to require users provide this extra info.

**Comment by jodh-intel** [comment]
As @jon mentioned, we should be using `git cherry-pick -x` as that adds are reference to the original commit in the commit message. We'll need to take care to retain that message if the commit message needs reworking to resolve non-git conflict build issues for example (as I had to deal with on https://github.com/kata-containers/runtime/pull/737 :).

**Comment by grahamwhaley** [comment]
OK, let me try to PR a docs update to add a section about stable branches and backports, with some best-methods and workflow.
@sboeuf - can you type here what labels you created and what the intended use of them is? I don't think I saw that written down did I? (or just ref if it is). iirc, there is 'bug' and 'feature', and therefore only PRs with 'bug' will go for stable backports, yes?

**Comment by sboeuf** [comment]
I have created `bug`, `feature`, `cleanup`, `vendor` and `stable-candidate`.
I think that it's been clear that stable branches should only get security or bug fixes, and for this reason, we should only try to backport the PR with the tag `bug` (might worth adding a tag `security-bug` if we want finer granularity).
But not all the PR tagged with `bug` are good `stable-candidate` since the bug might not be present in the stable branches, or for any other reasons.
Most of the time, we should ask authors about their opinion if this should be a `stable-candidate`.
Last thing, we want the backport to be done by the author, since they know the PR better than anyone, and this way we're not putting this backporting burden on a dedicated person.
